binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 4
brace_style = "AlwaysNextLine"
color = "Auto"
combine_control_expr = false
comment_width = 9999
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
empty_item_single_line = true
error_on_line_overflow = false
error_on_unformatted = false
fn_args_density = "Vertical"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = true
format_strings = true
hard_tabs = true
hide_parse_errors = false
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 9999
merge_derives = true
newline_style = "Unix"
normalize_comments = true
remove_blank_lines_at_start_or_end_of_block = false
reorder_extern_crates_in_group = true
reorder_extern_crates = true
reorder_imported_names = true
reorder_imports_in_group = true
reorder_imports = true
reorder_modules = true
report_fixme = "Never"
report_todo = "Never"
required_version = "0.4.1"
skip_children = false
space_after_colon = true
space_before_colon = true
spaces_around_ranges = true
spaces_within_parens_and_brackets = false
struct_field_align_threshold = 0
struct_lit_single_line = false
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = false
use_small_heuristics = false
use_try_shorthand = false
where_single_line = false
wrap_comments = false
write_mode = "Overwrite"
